# -*- coding: utf-8 -*-
"""Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UdulWYohLKexKjq3w9oV1lHHz3KY8Sl
"""

pip install numpy pandas scikit-learn matplotlib seaborn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, ConfusionMatrixDisplay
)

# reproducibility
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

iris = load_iris(as_frame=True)
X = iris.data                      # features (150×4)
y = iris.target                    # labels   (150,)
df = iris.frame                    # convenience DataFrame

print(df.head())
print("\nClass distribution:\n", pd.Series(y).value_counts())

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

clf = LogisticRegression(max_iter=1000, random_state=RANDOM_STATE)

cv_scores = cross_val_score(clf, X_train_scaled, y_train, cv=5, n_jobs=-1)
print(f"5‑fold CV accuracy: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")

clf.fit(X_train_scaled, y_train)

y_pred = clf.predict(X_test_scaled)
acc = accuracy_score(y_test, y_pred)
print(f"Hold‑out accuracy: {acc:.3f}\n")

print("Classification report:\n", classification_report(y_test, y_pred, target_names=iris.target_names))

cm = confusion_matrix(y_test, y_pred, labels=clf.classes_)
ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=iris.target_names).plot()
plt.title("Iris – Confusion Matrix (LogReg)")
plt.show()

sns.pairplot(df, hue="target", corner=True,
             vars=iris.feature_names,
             palette="bright")
plt.suptitle("Iris feature pairs coloured by species", y=1.02)
plt.show()

import joblib
joblib.dump({
    "model": clf,
    "scaler": scaler,
    "metadata": {
        "dataset": "iris",
        "accuracy": acc,
        "created_by": "Shrey",
        "created_on": "2025‑06‑14"
    }
}, "iris_logreg_model.joblib")

print("✅ Model dumped to iris_logreg_model.joblib")